name: ATProto Lexicon Tools
description: GitHub Actions for linting, validating, and publishing ATProto lexicons using the goat CLI
author: Birbhouse Games, LLC

branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - name: Usage Information
      shell: bash
      run: |
        echo "ATProto Lexicon Tools"
        echo "====================="
        echo ""
        echo "This is a collection of actions. Please use one of the following:"
        echo ""
        echo "  - birbhouse-games/lexicon-tools/lint@v1"
        echo "  - birbhouse-games/lexicon-tools/breaking@v1"
        echo "  - birbhouse-games/lexicon-tools/check-dns@v1"
        echo "  - birbhouse-games/lexicon-tools/status@v1"
        echo "  - birbhouse-games/lexicon-tools/publish@v1"
        echo ""
        echo "See: https://github.com/birbhouse-games/lexicon-tools"
